
apiVersion: apps/v1
kind: Deployment
metadata:
  name: srfe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextjs
  template:
    metadata:
      labels:
        app: nextjs
    spec:
      containers:
      - name: nextjs
        image: 471112789277.dkr.ecr.us-east-2.amazonaws.com/srfe:latest
        ports:
        - containerPort: 3000
